

def generateBody(idioma: str, importe: float, moneda: str, numeroPedido: int, diasFactura: str):
    """Genera el cuerpo del correo electrónico de solicitud de pago."""
    match idioma.lower():
        case "español" | "es":
            subject = f"Pendiente de pago proforma nº pedido {numeroPedido}"
            body = f"Estimado cliente,\n\nLe informamos de que, salvo error por nuestra parte, no hemos recibido el pago de la proforma por importe de {importe} {moneda} correspondiente al pedido número {numeroPedido} que le enviamos por correo hace {diasFactura} días.\n\nRogamos que proceda al pago de la misma, para que podamos enviarle su pedido a la mayor brevedad posible, en el caso de que no haya gestionado todavía su pago.\nRecuerde indicar como concepto de la transferencia únicamente el número de pedido. \nSi necesita más información, no dude en contactar con nosotros.\n\nGracias por su colaboración.\nUn saludo."
        case "english" | "en":
            subject = f"Payment not received for order {numeroPedido}"
            body = f"Dear Customer,\n\nWe would like to inform you that, unless there has been an error on our part, we have not yet received payment for the proforma invoice in the amount of {importe} {moneda} related to the order nº {numeroPedido} which we sent you {diasFactura} days ago.\n\nWe kindly ask you to proceed with the payment, if you have not already done so, so that we can ship your order as soon as possible. \nPlease make sure to indicate only the order number as the payment reference.\nWe remain at your disposal for any further information. \n\nThank you for your cooperation.\nKind regards,"
        case "français" | "fr":
            subject = f"Paiement non reçu pour la commande {numeroPedido}"
            body = f"Cher client,\n\nNous vous informons que, sauf erreur de notre part, nous n'avons pas reçu le paiement de la facture proforma d'un montant de {importe} {moneda} correspondant à la commande n° {numeroPedido} que nous vous avons envoyée par mail il y a {diasFactura} jours.\n\nNous vous prions de bien vouloir procéder au paiement, afin que nous puissions vous envoyer votre commande dans les plus brefs délais, si vous n'avez pas encore effectué votre paiement. \nN'oubliez pas d'indiquer uniquement le numéro de commande comme référence du virement.\nSi vous avez besoin de plus amples informations, n'hésitez pas à nous contacter. \n\nMerci d'avance.\nMeilleures salutations,"
        case "deutsch" | "de":
            subject = f"Zahlung nicht erhalten für die Bestellung {numeroPedido}"
            body = f"Sehr geehrter Kunde,\n\nwir möchten Sie darauf hinweisen, dass wir - vorbehaltlich eines Irrtums unsererseits – die Zahlung der Proforma-Rechnung über {importe} {moneda} für die Bestellung Nr. {numeroPedido} die wir Ihnen vor {diasFactura}  Tagen per E-Mail zugesandt haben, bislang nicht erhalten haben.\n\nWir bitten Sie, die Zahlung vorzunehmen, damit wir Ihre Bestellung so schnell wie möglich versenden können, falls Sie die Überweisung noch nicht veranlasst haben. \nBitte geben Sie als Zahlungsreferenz ausschließlich die Bestellnummer an.\nSollten Sie weitere Informationen benötigen, zögern Sie bitte nicht, uns zu kontaktieren.\n\nVielen Dank im Voraus.\nMit freundlichen Grüßen,"
        case "italiano" | "it":
            subject = f"Pagamento non ricevuto per l'ordine {numeroPedido}"
            body = f"Gentile cliente,\n\nLa informiamo che, salvo nostro errore, non abbiamo ancora ricevuto il pagamento della fattura proforma dell’importo di {importe} {moneda} relativa all'ordine nº {numeroPedido} che le abbiamo inviato {diasFactura} giorni fa.\n\nLa preghiamo gentilmente di provvedere al pagamento, qualora non lo avesse ancora effettuato, così da poter procedere con la spedizione del suo ordine il prima possibile.\nLa invitiamo inoltre a indicare solo il numero dell’ordine come concetto del bonifico.\nRestiamo a sua disposizione per qualsiasi ulteriore informazione.\n\nLa ringraziamo per la collaborazione.\nCordiali saluti,"
        case "português" | "pt":
            subject = f"Pagamento não recebido para o pedido {numeroPedido}"
            body = f"Estimado cliente,\n\nInformamos que, salvo erro da nossa parte, não recebemos o pagamento da factura proforma pelo valor de {importe} {moneda}, que corresponde ao pedido nº {numeroPedido}, que lhe enviámos por correio faz já {diasFactura} dias.\n\nPedimos que proceda ao seu pagamento, para que possamos enviar-lhe o pedido com a maior brevidade possível. \nRecordamos para que quando fizer a transferência coloque a indicação do nº de pedido para que possamos saber de quem é a transferência. \nAo seu dispor para qualquer informação adicional.\n\nAgradecemos a atenção dispensada. \nCordialmente,"
        case "rumano" | "ro":
            subject = f"Plată neprimita pentru comanda {numeroPedido}"
            body = f"Stimate client,\n\nVă informăm că, cu excepția unei eventuale greșeli din partea noastră, nu am primit plata proformei în valoare de {importe} {moneda} aferentă comenzii nr. {numeroPedido} pe care v-am trimis-o prin e-mail acum {diasFactura} zile.\n\nVă rugăm să efectuați plata acesteia pentru a putea expedia comanda dumneavoastră cât mai curând posibil, în cazul în care nu ați realizat încă plata. \nVă rugăm să menționați ca descriere a transferului doar numărul comenzii.\nDacă aveți nevoie de informații suplimentare, nu ezitați să ne contactați.\n\nVă mulțumim anticipat,\nCu stim"
        case _:
            subject = f"Payment not received for order {numeroPedido}"
            body = f"Dear Customer,\n\nWe would like to inform you that, unless there has been an error on our part, we have not yet received payment for the proforma invoice in the amount of {importe} {moneda} related to the order nº {numeroPedido} which we sent you {diasFactura} days ago.\n\nWe kindly ask you to proceed with the payment, if you have not already done so, so that we can ship your order as soon as possible. \nPlease make sure to indicate only the order number as the payment reference.\nWe remain at your disposal for any further information. \n\nThank you for your cooperation.\nKind regards,"

    return body, subject